/*
 * ◊Ó÷’…’ ¥2_nosolve20W.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Jan 26 2026, 10:20 by COMSOL 6.3.0.290. */
public class ◊Ó÷’…’ ¥2_nosolve20W {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model.modelPath("D:\\COMSOL\\data");

    model.label("\u6700\u7ec8\u70e7\u86802_nosolve20W.mph");

    model.param().set("Lx", "15[mm]");
    model.param().set("Ly", "15[mm]");
    model.param().set("t0", "1[mm]");
    model.param().set("P_laser", "10.503[W]");
    model.param().set("w0", "0.5[mm]");
    model.param().set("x0", "0[mm]");
    model.param().set("y0", "0[mm]");
    model.param().set("A_abs_v", "0.90");
    model.param().set("A_abs_c", "0.95");
    model.param().set("T_amb", "293.15[K]");
    model.param().set("h_conv", "15[W/(m^2*K)]");
    model.param().set("eps_surf", "0.90");
    model.param().set("sigmaSB", "5.670374419e-8[W/(m^2*K^4)]");
    model.param().set("Rgas", "8.314462618[J/(mol*K)]");
    model.param().set("Ap", "7.0e8[1/s]");
    model.param().set("Ep", "163e3[J/mol]");
    model.param().set("np", "0.6");
    model.param().set("theta", "0.19");
    model.param().set("Ac", "3.5e6[1/s]");
    model.param().set("Ec", "139e3[J/mol]");
    model.param().set("nc", "0.6");
    model.param().set("Af", "2.0e7[1/s]");
    model.param().set("Ef", "162e3[J/mol]");
    model.param().set("nf", "0.8");
    model.param().set("H_pyro", "6.70e5[J/kg]");
    model.param().set("H_ox", "3.276e7[J/kg]");
    model.param().set("drxn", "65[um]");
    model.param()
         .set("Vf", "0.60", "\u7ea4\u7ef4\u4f53\u79ef\u5206\u6570\uff0c\u5e73\u7eb9/\u659c\u7eb9\u5e38\u89c1\u91cf\u7ea7");
    model.param().set("Vr", "1-Vf");
    model.param().set("rho_res", "1200[kg/m^3]");
    model.param().set("rho_cf", "1760[kg/m^3]");
    model.param().set("rho_char", "375[kg/m^3]");
    model.param().set("cp_res", "1200[J/(kg*K)]");
    model.param().set("cp_cf", "710[J/(kg*K)]");
    model.param().set("cp_char", "1000[J/(kg*K)]");
    model.param().set("k_res", "0.25[W/(m*K)]");
    model.param().set("k_cf_in", "6[W/(m*K)]");
    model.param().set("k_cf_z", "1[W/(m*K)]");
    model.param().set("k_char_th", "0.82[W/(m*K)]");
    model.param().set("yO2", "0.21");
    model.param().set("p_amb", "1[atm]");
    model.param().set("M_C", "0.012011[kg/mol]");
    model.param().set("nuC", "2");
    model.param().set("rho_gas", "1.2[kg/m^3]");
    model.param().set("cp_gas", "1005[J/(kg*K)]");
    model.param().set("Pr", "0.71");
    model.param().set("Sc", "0.84");
    model.param().set("eps_min", "1e-6");
    model.param().set("D_eff_min", "1e-12[m^2/s]");
    model.param().set("Phi_eps", "1e-4");
    model.param().set("tauL", "1e-4[s]");
    model.param().set("dT_s", "150[K]");
    model.param().set("dz_s", "2e-5[m]");
    model.param().set("da_s", "1e-3");
    model.param().set("dx_s", "1e-9");
    model.param().set("du_s", "1e-8[m]");
    model.param().set("eps_a", "1e-6");
    model.param().set("dq_s", "1e-6[W/m^2]");
    model.param().set("den_s", "1e-6[J/m^2]");
    model.param().set("dr_s", "1e-6[1/s]");
    model.param().set("t_ablate_target", "100[s]");
    model.param().set("D_O2_ref", "2.0e-5[m^2/s]");
    model.param().set("M_C3", "0.03603[kg/mol]");
    model.param().set("H_sub", "5.96e7[J/kg]");
    model.param().set("alpha_sub", "1");
    model.param().set("T_on_sub", "3000[K]");
    model.param().set("dT_sub", "150[K]");
    model.param().set("Ru", "8.314462618[J/(mol*K)]");
    model.param().set("M_C2", "0.024022[kg/mol]");
    model.param().set("alpha_C", "0.14");
    model.param().set("alpha_C2", "0.26");
    model.param().set("alpha_C3", "0.03");
    model.param().set("P_C", "-85715[K]");
    model.param().set("P_C2", "-98363[K]");
    model.param().set("P_C3", "-93227[K]");
    model.param().set("Q_C", "18.69");
    model.param().set("Q_C2", "22.20");
    model.param().set("Q_C3", "23.93");
    model.param().set("dZ_smooth", "13[um]");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 3);

    model.result().table().create("tbl1", "Table");

    model.component("comp1").func().create("step1", "Step");
    model.component("comp1").func().create("step2", "Step");
    model.component("comp1").func().create("step3", "Step");
    model.component("comp1").func().create("an1", "Analytic");
    model.component("comp1").func().create("an2", "Analytic");
    model.component("comp1").func().create("an3", "Analytic");
    model.component("comp1").func().create("an4", "Analytic");
    model.component("comp1").func().create("an5", "Analytic");
    model.component("comp1").func().create("an6", "Analytic");
    model.component("comp1").func().create("an7", "Analytic");
    model.component("comp1").func().create("an8", "Analytic");
    model.component("comp1").func().create("an9", "Analytic");
    model.component("comp1").func().create("an10", "Analytic");
    model.component("comp1").func().create("step4", "Step");
    model.component("comp1").func("step1").set("funcname", "stepT");
    model.component("comp1").func("step1").set("location", "700[K]");
    model.component("comp1").func("step1").set("smooth", "200[K]");
    model.component("comp1").func("step1").set("locationdef", "beginning");
    model.component("comp1").func("step2").set("funcname", "stepZ");
    model.component("comp1").func("step2").set("location", "(t0/2 - drxn)");
    model.component("comp1").func("step2").set("smooth", "drxn/5");
    model.component("comp1").func("step2").set("locationdef", "beginning");
    model.component("comp1").func("step3").set("funcname", "stepP");
    model.component("comp1").func("step3").set("location", "0.1[ms]");
    model.component("comp1").func("step3").set("smooth", "0.05[ms]");
    model.component("comp1").func("an1").set("funcname", "rampL");
    model.component("comp1").func("an1").set("expr", "0.5*(1+tanh((t-3*tauL)/tauL))");
    model.component("comp1").func("an1").set("args", new String[]{"t"});
    model.component("comp1").func("an1").set("fununit", "1");
    model.component("comp1").func("an1").set("argunit", new String[]{"s"});
    model.component("comp1").func("an1").set("plotargs", new String[][]{{"t", "0", "1e-3"}});
    model.component("comp1").func("an2").set("funcname", "Hs");
    model.component("comp1").func("an2").set("expr", "flc2hs(x,d)");
    model.component("comp1").func("an2").set("args", new String[]{"x", "d"});
    model.component("comp1").func("an2").set("argunit", new String[]{"", ""});
    model.component("comp1").func("an2").set("plotaxis", new String[]{"on", "on"});
    model.component("comp1").func("an2").set("plotfixedvalue", new String[]{"0", "0"});
    model.component("comp1").func("an2").set("plotargs", new String[][]{{"x", "0", "1"}, {"d", "0", "1"}});
    model.component("comp1").func("an3").set("funcname", "smax");
    model.component("comp1").func("an3").set("expr", "a + (b-a)*flc2hs(b-a, d)");
    model.component("comp1").func("an3").set("args", new String[]{"a", "b", "d"});
    model.component("comp1").func("an3").set("argunit", new String[]{"", "", ""});
    model.component("comp1").func("an3").set("plotaxis", new String[]{"on", "off", "off"});
    model.component("comp1").func("an3").set("plotfixedvalue", new String[]{"0", "0", "0"});
    model.component("comp1").func("an3")
         .set("plotargs", new String[][]{{"a", "0", "1"}, {"b", "0", "1"}, {"d", "0", "1"}});
    model.component("comp1").func("an4").set("funcname", "smin");
    model.component("comp1").func("an4").set("expr", "b - (b-a)*flc2hs(b-a, d)");
    model.component("comp1").func("an4").set("args", new String[]{"a", "b", "d"});
    model.component("comp1").func("an4").set("argunit", new String[]{"", "", ""});
    model.component("comp1").func("an4").set("plotaxis", new String[]{"on", "on", "on"});
    model.component("comp1").func("an4").set("plotfixedvalue", new String[]{"0", "0", "0"});
    model.component("comp1").func("an4")
         .set("plotargs", new String[][]{{"a", "0", "1"}, {"b", "0", "1"}, {"d", "0", "1"}});
    model.component("comp1").func("an5").set("funcname", "clamp01");
    model.component("comp1").func("an5").set("expr", "smin( smax(x, 0, d), 1, d )");
    model.component("comp1").func("an5").set("args", new String[]{"x", "d"});
    model.component("comp1").func("an5").set("argunit", new String[]{"", ""});
    model.component("comp1").func("an5").set("plotaxis", new String[]{"on", "on"});
    model.component("comp1").func("an5").set("plotfixedvalue", new String[]{"0", "0"});
    model.component("comp1").func("an5").set("plotargs", new String[][]{{"x", "0", "1"}, {"d", "0", "1"}});
    model.component("comp1").func("an6").set("funcname", "pos");
    model.component("comp1").func("an6").set("expr", "smax(x, 0, d)");
    model.component("comp1").func("an6").set("args", new String[]{"x", "d"});
    model.component("comp1").func("an6").set("argunit", new String[]{"", ""});
    model.component("comp1").func("an6").set("plotaxis", new String[]{"on", "on"});
    model.component("comp1").func("an6").set("plotfixedvalue", new String[]{"0", "0"});
    model.component("comp1").func("an6").set("plotargs", new String[][]{{"x", "0", "1"}, {"d", "0", "1"}});
    model.component("comp1").func("an7").set("funcname", "neg");
    model.component("comp1").func("an7").set("expr", "smin(x, 0, d)");
    model.component("comp1").func("an7").set("args", new String[]{"x", "d"});
    model.component("comp1").func("an7").set("argunit", new String[]{"", ""});
    model.component("comp1").func("an7").set("plotaxis", new String[]{"on", "on"});
    model.component("comp1").func("an7").set("plotfixedvalue", new String[]{"0", "0"});
    model.component("comp1").func("an7").set("plotargs", new String[][]{{"x", "0", "1"}, {"d", "0", "1"}});
    model.component("comp1").func("an8").set("funcname", "abs_s");
    model.component("comp1").func("an8").set("expr", "sqrt(x^2 + d^2)");
    model.component("comp1").func("an8").set("args", new String[]{"x", "d"});
    model.component("comp1").func("an8").set("argunit", new String[]{"", ""});
    model.component("comp1").func("an8").set("plotaxis", new String[]{"on", "on"});
    model.component("comp1").func("an8").set("plotfixedvalue", new String[]{"0", "0"});
    model.component("comp1").func("an8").set("plotargs", new String[][]{{"x", "0", "1"}, {"d", "0", "1"}});
    model.component("comp1").func("an9").set("funcname", "inv_s");
    model.component("comp1").func("an9").set("expr", "1/smax(abs_s(x,d), d, d)");
    model.component("comp1").func("an9").set("args", new String[]{"x", "d"});
    model.component("comp1").func("an9").set("argunit", new String[]{"", ""});
    model.component("comp1").func("an9").set("plotaxis", new String[]{"on", "on"});
    model.component("comp1").func("an9").set("plotfixedvalue", new String[]{"0", "0"});
    model.component("comp1").func("an9").set("plotargs", new String[][]{{"x", "0", "1"}, {"d", "0", "1"}});
    model.component("comp1").func("an10").set("funcname", "psatC");
    model.component("comp1").func("an10").set("expr", "5.19e15*exp(-90845/T)");
    model.component("comp1").func("an10").set("args", new String[]{"T"});
    model.component("comp1").func("an10").set("fununit", "Pa");
    model.component("comp1").func("an10").set("argunit", new String[]{"K"});
    model.component("comp1").func("an10").set("plotargs", new String[][]{{"T", "2000", "4000"}});
    model.component("comp1").func("step4").active(false);
    model.component("comp1").func("step4").set("funcname", "step_sub");
    model.component("comp1").func("step4").set("location", "T_on_sub");
    model.component("comp1").func("step4").set("smooth", "dT_sub");

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").geom("geom1").lengthUnit("mm");
    model.component("comp1").geom("geom1").geomRep("cadps");
    model.component("comp1").geom("geom1").designBooleans(true);
    model.component("comp1").geom("geom1").create("blk1", "Block");
    model.component("comp1").geom("geom1").feature("blk1").set("size", new String[]{"Lx", "Ly", "t0"});
    model.component("comp1").geom("geom1").feature("blk1").set("base", "center");
    model.component("comp1").geom("geom1").create("wp1", "WorkPlane");
    model.component("comp1").geom("geom1").feature("wp1").set("planetype", "faceparallel");
    model.component("comp1").geom("geom1").feature("wp1").set("unite", true);
    model.component("comp1").geom("geom1").feature("wp1").selection("face").set("blk1(1)", 4);
    model.component("comp1").geom("geom1").feature("wp1").geom().create("sq1", "Square");
    model.component("comp1").geom("geom1").feature("wp1").geom().feature("sq1").set("base", "center");
    model.component("comp1").geom("geom1").create("blk2", "Block");
    model.component("comp1").geom("geom1").feature("blk2").active(false);
    model.component("comp1").geom("geom1").feature("blk2").set("size", new int[]{50, 50, 30});
    model.component("comp1").geom("geom1").feature("blk2").set("base", "center");
    model.component("comp1").geom("geom1").feature("blk2").set("pos", new int[]{0, 0, 10});
    model.component("comp1").geom("geom1").create("wp2", "WorkPlane");
    model.component("comp1").geom("geom1").feature("wp2").active(false);
    model.component("comp1").geom("geom1").feature("wp2").set("quickz", "t0/2 - drxn");
    model.component("comp1").geom("geom1").feature("wp2").set("unite", true);
    model.component("comp1").geom("geom1").create("par1", "Partition");
    model.component("comp1").geom("geom1").feature("par1").active(false);
    model.component("comp1").geom("geom1").feature("par1").set("partitionwith", "workplane");
    model.component("comp1").geom("geom1").feature("par1").set("propagatesel", false);
    model.component("comp1").geom("geom1").feature("par1").selection("input").set("blk1");
    model.component("comp1").geom("geom1").create("mcf1", "MeshControlFaces");
    model.component("comp1").geom("geom1").feature("mcf1").selection("input").set("fin(1)", 6);
    model.component("comp1").geom("geom1").run();
    model.component("comp1").geom("geom1").run("par1");

    model.component("comp1").selection().create("sel1", "Explicit");
    model.component("comp1").selection("sel1").set(1);
    model.component("comp1").selection().create("sel2", "Explicit");
    model.component("comp1").selection("sel1").label("\u539a\u5ea6 drxn\uff08\u53cd\u5e94\u5c42\uff09");
    model.component("comp1").selection("sel2").label("\u5176\u4f59\u539a\u5ea6\uff08\u4e3b\u4f53\u5c42\uff09");

    model.component("comp1").variable().create("var1");
    model.component("comp1").variable("var1").set("r2", "(x-x0)^2+(y-y0)^2");
    model.component("comp1").variable("var1").set("Abs_eff", "A_abs_v*(1-alphap01) + A_abs_c*alphap01");
    model.component("comp1").variable("var1")
         .set("q_laser", "rampL(t)*Abs_eff*(2*P_laser/(pi*w0^2))*exp(-2*r2/(w0^2))");
    model.component("comp1").variable("var1").set("dalphap_dt", "alphapt");
    model.component("comp1").variable("var1").set("dalphac_dt", "alphact");
    model.component("comp1").variable("var1").set("dalphaf_dt", "alphaft");
    model.component("comp1").variable("var1").set("Q_pyro", "-(Vr*rho_res)*H_pyro*dalphap_dt");
    model.component("comp1").variable("var1").set("Q_ox_char", "+(Vr*rho_res*theta*alphap01)*H_ox*dalphac_dt");
    model.component("comp1").variable("var1").set("Q_ox_fib", "+(Vf*rho_cf)*H_ox*dalphaf_dt");
    model.component("comp1").variable("var1").set("Q_total", "Q_pyro + Q_ox_char + Q_ox_fib");
    model.component("comp1").variable("var1")
         .set("mdot_vol", "(Vr*rho_res*(1-theta))*dalphap_dt +(Vr*rho_res*theta*alphap01)*dalphac_dt + (Vf*rho_cf)*dalphaf_dt");
    model.component("comp1").variable("var1")
         .set("rho_eff", "Vf*rho_cf + Vr*rho_res*(1-alphap01) +Vr*rho_char*theta*alphap01*(1-alphac01)");
    model.component("comp1").variable("var1").set("v_rec", "mdot_rec_vol*drxn/rho_eff");
    model.component("comp1").variable("var1").set("v_mesh", "stepT(T)*v_rec");
    model.component("comp1").variable("var1")
         .set("cp_eff", "(Vf*rho_cf*cp_cf + Vr*rho_res*(1-alphap01)*cp_res + Vr*rho_char*theta*alphap01*cp_char) / ( 1e-6[kg/m^3] + (rho_eff-1e-6[kg/m^3])*flc2hs(rho_eff-1e-6[kg/m^3], 1e-6[kg/m^3]) )");
    model.component("comp1").variable("var1").set("mdot_pyro_vol", "Vr*rho_res*(1-theta)*dalphap_dt [kg/m^3/s]");
    model.component("comp1").variable("var1")
         .set("mdot_ox_vol", "(Vr*rho_res*theta*alphap)*dalphac_dt + (Vf*rho_cf)*dalphaf_dt");
    model.component("comp1").variable("var1").set("mdot_rec_vol", "mdot_ox_vol + mdot_sub_vol");
    model.component("comp1").variable("var1").set("mdot_sub_vol", "0");
    model.component("comp1").variable("var1").set("f_CO", "1");
    model.component("comp1").variable("var1").set("nuO2_per_C", "1-0.5*f_CO");
    model.component("comp1").variable("var1").set("dH_CO", "110.53[kJ/mol]");
    model.component("comp1").variable("var1").set("dH_CO2", "393.51[kJ/mol]");
    model.component("comp1").variable("var1").set("dH_ox_mol", "f_CO*dH_CO + (1-f_CO)*dH_CO2");
    model.component("comp1").variable("var1").set("H_ox", "dH_ox_mol / M_C");
    model.component("comp1").variable("var1").set("cO2_inf", "yO2*p_amb/(R_const*T_amb)");
    model.component("comp1").variable("var1").set("D_O2", "D_O2_ref*(T/T_amb)^1.75*(p_amb/p)");
    model.component("comp1").variable("var1").set("Le", "Sc/Pr");
    model.component("comp1").variable("var1").set("k_m", "(h_conv/(rho_gas*cp_gas))*Le^(-2/3)");
    model.component("comp1").variable("var1").set("J_O2_max", "k_m*cO2_inf");
    model.component("comp1").variable("var1").set("mCdot_max_surf", "(J_O2_max/nuO2_per_C)*M_C");
    model.component("comp1").variable("var1").set("mdot_ox_max_vol", "mCdot_max_surf/drxn");
    model.component("comp1").variable("var1")
         .set("scale_O2_m", "mdot_ox_max_vol/(mdot_ox_kin_vol + mdot_ox_max_vol + 1e-12[kg/(m^3*s)])");
    model.component("comp1").variable("var1")
         .set("mdot_ox_kin_vol", "Vr*rho_res*theta*alphap01*dalphac_dt_kin + Vf*rho_cf*dalphaf_dt_kin");
    model.component("comp1").variable("var1").set("p", "p_amb");
    model.component("comp1").variable("var1").set("v_sub", "mdot_sub/rho_eff");
    model.component("comp1").variable("var1").set("q_sub", "-mdot_sub*H_sub");
    model.component("comp1").variable("var1").set("mdot_pyro_surf", "(Vr*rho_res*(1-theta))*dalphap_dt*drxn");
    model.component("comp1").variable("var1").set("v_pyro", "mdot_pyro_surf/rho_eff");
    model.component("comp1").variable().create("var2");
    model.component("comp1").variable("var2").set("C_O2_amb", "yO2*p_amb/(Rgas*T_amb)");
    model.component("comp1").variable("var2").set("h_m", "(h_conv/(rho_gas*cp_gas))*(Sc/Pr)^(2/3)");
    model.component("comp1").variable("var2").set("R_C_max", "J_O2_max*(nuC*M_C)/drxn");
    model.component("comp1").variable("var2")
         .set("dalphac_dt_kin", "stepZ(Z)*Ac*exp(-Ec/(Rgas*T))*( 1e-6 + ((1-alphac01)-1e-6)*flc2hs((1-alphac01)-1e-6, 1e-6) )^nc * alphap01");
    model.component("comp1").variable("var2")
         .set("dalphaf_dt_kin", "stepZ(Z)*Af*exp(-Ef/(Rgas*T))*( 1e-6 + ((1-alphaf01)-1e-6)*flc2hs((1-alphaf01)-1e-6, 1e-6) )^nf");
    model.component("comp1").variable("var2").set("R_C_char_kin", "dalphac_dt_kin*(Vr*rho_res*theta*alphap01)");
    model.component("comp1").variable("var2").set("R_C_fib_kin", "dalphaf_dt_kin*(Vf*rho_cf)");
    model.component("comp1").variable("var2").set("R_C_total_kin", "R_C_char_kin + R_C_fib_kin");
    model.component("comp1").variable("var2")
         .set("scale_O2", "R_C_max/(R_C_total_kin + R_C_max + 1e-9[kg/(m^3*s)])");
    model.component("comp1").variable("var2").set("D_O2_bulk", "1.8e-5[m^2/s]*(T/273.15[K])^1.75*(1[atm]/p_amb)");
    model.component("comp1").variable("var2").set("rho_virgin", "Vf*rho_cf + Vr*rho_res");
    model.component("comp1").variable("var2")
         .set("eps_pore", "eps_min + (eps_raw-eps_min)*flc2hs(eps_raw-eps_min, eps_min)");
    model.component("comp1").variable("var2")
         .set("D_eff", "D_eff_min + (D_eff_raw-D_eff_min)*flc2hs(D_eff_raw-D_eff_min, D_eff_min)");
    model.component("comp1").variable("var2").set("Phi_char", "sqrt( (drxn^2)*(k_ox_char/D_eff) + (Phi_eps^2) )");
    model.component("comp1").variable("var2").set("eta_char", "1");
    model.component("comp1").variable("var2").set("eps_raw", "1 - rho_eff/rho_virgin");
    model.component("comp1").variable("var2").set("D_eff_raw", "D_O2_bulk*eps_pore^1.5");
    model.component("comp1").variable("var2")
         .set("Phi_char_c", "Phi_eps + (Phi_char-Phi_eps)*flc2hs(Phi_char-Phi_eps, Phi_eps)");
    model.component("comp1").variable("var2").set("k_ox_char", "stepZ(Z)*Ac*exp(-Ec/(Rgas*T))");
    model.component("comp1").variable("var2").set("Q_ox_vol", "(R_C_char_kin*scale_O2)*H_ox");
    model.component("comp1").variable("var2")
         .set("mdot_sub1", "step_sub(T)*alpha_sub*psatC(T)*sqrt(M_C3/(2*pi*R_const*T))");
    model.component("comp1").variable().create("var3");
    model.component("comp1").variable("var3").set("alphap01", "clamp01(alphap, da_s)");
    model.component("comp1").variable("var3").set("alphac01", "clamp01(alphac, da_s)");
    model.component("comp1").variable("var3").set("alphaf01", "clamp01(alphaf, da_s)");
    model.component("comp1").variable("var3").set("one_m_alphac", "smax(1 - alphac01, dx_s, dx_s)");
    model.component("comp1").variable("var3").set("one_m_alphap", "smax(1 - alphap01, dx_s, dx_s)");
    model.component("comp1").variable("var3").set("alphap_pos", "smax(alphap01, dx_s, dx_s)");
    model.component("comp1").variable("var3")
         .set("r_py", "Ap*exp(-Ep/(Rgas*T))*( smax(1-alphap01, eps_a, eps_a)^np )");
    model.component("comp1").variable("var3")
         .set("qpos", "0[W/m^2] + (q_laser-0[W/m^2])*flc2hs(q_laser-0[W/m^2], dq_s)");
    model.component("comp1").variable("var3")
         .set("denA", "den_s + (Vr*rho_res*H_pyro*drxn - den_s)*flc2hs(Vr*rho_res*H_pyro*drxn - den_s, den_s)");
    model.component("comp1").variable("var3").set("r_cap", "qpos/denA");
    model.component("comp1").variable("var3")
         .set("rem_p", "eps_a + ((1-alphap01)-eps_a)*flc2hs((1-alphap01)-eps_a, eps_a)");
    model.component("comp1").variable("var3").set("r_kin", "Ap*exp(-Ep/(Rgas*T))*(rem_p^np)");
    model.component("comp1").variable("var3").set("r_lim", "r_cap + (r_kin - r_cap)*flc2hs(r_cap - r_kin, dr_s)");
    model.component("comp1").variable("var3").set("gate", "flc2hs(1-alphap01, da_s)");
    model.component("comp1").variable("var3").set("f_py", "r_lim*gate");
    model.component("comp1").variable().create("var4");
    model.component("comp1").variable("var4").set("Tw", "max(T, 300[K])");
    model.component("comp1").variable("var4").set("pv_C", "101300[Pa]*exp(P_C/Tw + Q_C)");
    model.component("comp1").variable("var4").set("pv_C2", "101300[Pa]*exp(P_C2/Tw + Q_C2)");
    model.component("comp1").variable("var4").set("pv_C3", "101300[Pa]*exp(P_C3/Tw + Q_C3)");
    model.component("comp1").variable("var4").set("pC", "0[Pa]");
    model.component("comp1").variable("var4").set("pC2", "0[Pa]");
    model.component("comp1").variable("var4").set("pC3", "0[Pa]");
    model.component("comp1").variable("var4").set("mdotC", "alpha_C *(pv_C - pC )*sqrt(M_C /(2*pi*Ru*Tw))");
    model.component("comp1").variable("var4").set("mdotC2", "alpha_C2*(pv_C2-pC2)*sqrt(M_C2/(2*pi*Ru*Tw))");
    model.component("comp1").variable("var4").set("mdotC3", "alpha_C3*(pv_C3-pC3)*sqrt(M_C3/(2*pi*Ru*Tw))");
    model.component("comp1").variable("var4").set("mdot_sub_raw", "mdotC + mdotC2 + mdotC3");
    model.component("comp1").variable("var4")
         .set("q_net", "max(q_laser+ h_conv*(T_amb - T) + eps_surf*sigmaSB*(T_amb^4 - T^4),0[W/m^2])");
    model.component("comp1").variable("var4").set("q_conv", "h_conv*(T_amb - T)");
    model.component("comp1").variable("var4").set("q_rad", "eps_surf*sigmaSB*(T_amb^4 - T^4)");
    model.component("comp1").variable("var4").set("mdot_sub_cap", "q_net/H_sub");
    model.component("comp1").variable("var4").set("step_sub", "flc2hs(T - T_on_sub, dT_sub)");
    model.component("comp1").variable("var4").set("mdot_sub", "min(mdot_sub_raw, mdot_sub_cap)");

    model.component("comp1").view("view3").tag("view5");
    model.view().create("view3", 3);
    model.view().create("view4", 3);
    model.view().create("view6", 2);

    model.component("comp1").material().create("CFRP_eff", "Common");

    model.component("comp1").physics().create("ht", "HeatTransfer", "geom1");
    model.component("comp1").physics("ht").create("hs1", "HeatSource", 3);
    model.component("comp1").physics("ht").feature("hs1").selection().set(1);
    model.component("comp1").physics("ht").create("hf1", "HeatFluxBoundary", 2);
    model.component("comp1").physics("ht").feature("hf1").selection().set(4, 6);
    model.component("comp1").physics("ht").create("hf2", "HeatFluxBoundary", 2);
    model.component("comp1").physics("ht").feature("hf2").selection().all();
    model.component("comp1").physics("ht").create("sar1", "SurfaceToAmbientRadiation", 2);
    model.component("comp1").physics("ht").feature("sar1").selection().all();
    model.component("comp1").physics().create("dode", "DomainODE", "geom1");
    model.component("comp1").physics("dode").field("dimensionless").component(new String[]{"alphap"});
    model.component("comp1").physics().create("dode2", "DomainODE", "geom1");
    model.component("comp1").physics("dode2").field("dimensionless").component(new String[]{"alphac"});
    model.component("comp1").physics().create("dode3", "DomainODE", "geom1");
    model.component("comp1").physics("dode3").field("dimensionless").component(new String[]{"alphaf"});
    model.component("comp1").physics().create("dg", "DeformedGeometry", "geom1");
    model.component("comp1").physics("dg").create("free1", "FreeDeformation", 3);
    model.component("comp1").physics("dg").feature("free1").selection().set(1);
    model.component("comp1").physics("dg").create("disp2", "PrescribedMeshDisplacement", 2);
    model.component("comp1").physics("dg").feature("disp2").selection().set(3);
    model.component("comp1").physics("dg").create("pnmv1", "PrescribedNormalMeshVelocity", 2);
    model.component("comp1").physics("dg").feature("pnmv1").selection().set(4, 6);
    model.component("comp1").physics("dg").create("disp3", "PrescribedMeshDisplacement", 2);
    model.component("comp1").physics("dg").feature("disp3").selection().set(1, 7);
    model.component("comp1").physics("dg").create("disp4", "PrescribedMeshDisplacement", 2);
    model.component("comp1").physics("dg").feature("disp4").selection().set(2, 5);

    model.component("comp1").mesh("mesh1").create("swe1", "Sweep");
    model.component("comp1").mesh("mesh1").create("swe2", "Sweep");
    model.component("comp1").mesh("mesh1").feature("swe1").create("size1", "Size");
    model.component("comp1").mesh("mesh1").feature("swe1").create("size2", "Size");
    model.component("comp1").mesh("mesh1").feature("swe1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").selection().geom("geom1", 2);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").selection().set(6);
    model.component("comp1").mesh("mesh1").feature("swe2").create("size1", "Size");
    model.component("comp1").mesh("mesh1").feature("swe2").create("size2", "Size");
    model.component("comp1").mesh("mesh1").feature("swe2").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("swe2").feature("size1").selection().geom("geom1", 3);
    model.component("comp1").mesh("mesh1").feature("swe2").feature("size1").selection().set(1);
    model.component("comp1").mesh("mesh1").feature("swe2").feature("size2").selection().geom("geom1", 2);
    model.component("comp1").mesh("mesh1").feature("swe2").feature("size2").selection().set(6);

    model.component("comp1").probe().create("bnd1", "Boundary");
    model.component("comp1").probe().create("bnd2", "Boundary");
    model.component("comp1").probe().create("bnd3", "Boundary");
    model.component("comp1").probe().create("dom1", "Domain");
    model.component("comp1").probe().create("dom2", "Domain");
    model.component("comp1").probe().create("dom3", "Domain");
    model.component("comp1").probe().create("dom4", "Domain");
    model.component("comp1").probe().create("dom5", "Domain");
    model.component("comp1").probe().create("dom6", "Domain");
    model.component("comp1").probe().create("dom7", "Domain");
    model.component("comp1").probe().create("bnd4", "Boundary");
    model.component("comp1").probe().create("bnd5", "Boundary");
    model.component("comp1").probe("bnd1").selection().set(6);
    model.component("comp1").probe("bnd2").selection().set(4, 6);
    model.component("comp1").probe("bnd3").selection().set(4, 6);
    model.component("comp1").probe("bnd5").selection().set(3);

    model.result().table("tbl1").label("\u63a2\u9488\u8868 1");

    model.component("comp1").variable("var2").label("\u6c27\u4f9b\u7ed9\u5c01\u9876\u53d8\u91cf");
    model.component("comp1").variable("var3").label("\u5e73\u6ed1");

    model.component("comp1").view("view2").axis().set("xmin", -23.50144386291504);
    model.component("comp1").view("view2").axis().set("xmax", 20.221010208129883);
    model.component("comp1").view("view2").axis().set("ymin", -33.477108001708984);
    model.component("comp1").view("view2").axis().set("ymax", 29.003690719604492);
    model.component("comp1").view("view5").label("\u89c6\u56fe 5");
    model.component("comp1").view("view5").axis().set("xmin", -8.6196928024292);
    model.component("comp1").view("view5").axis().set("xmax", 8.6196928024292);
    model.component("comp1").view("view5").axis().set("ymin", -12.345623970031738);
    model.component("comp1").view("view5").axis().set("ymax", 12.345623970031738);
    model.view("view6").axis().set("viewscaletype", "automatic");

    model.component("comp1").material("CFRP_eff").label("\u6750\u6599 1");
    model.component("comp1").material("CFRP_eff").propertyGroup("def").set("density", "rho_eff");
    model.component("comp1").material("CFRP_eff").propertyGroup("def")
         .set("thermalconductivity", new String[]{"Vf*k_cf_in+Vr*(1-alphap01)*k_res+Vr*alphap01*k_char_th", "0", "0", "0", "Vf*k_cf_in+Vr*(1-alphap01)*k_res+Vr*alphap01*k_char_th", "0", "0", "0", "Vf*k_cf_z+Vr*(1-alphap01)*k_res+Vr*alphap01*k_char_th"});
    model.component("comp1").material("CFRP_eff").propertyGroup("def").set("heatcapacity", "cp_eff");

    model.component("comp1").physics("ht").feature("init1").set("Tinit", "T_amb");
    model.component("comp1").physics("ht").feature("hs1").set("Q0", "Q_total");
    model.component("comp1").physics("ht").feature("hs1").label("\u53cd\u5e94\u70ed");
    model.component("comp1").physics("ht").feature("hf1").set("q0_input", "q_laser- mdot_sub*H_sub");
    model.component("comp1").physics("ht").feature("hf1").set("materialType", "solid");
    model.component("comp1").physics("ht").feature("hf1").label("\u6fc0\u5149\u70ed\u6d41");
    model.component("comp1").physics("ht").feature("hf2").set("HeatFluxType", "ConvectiveHeatFlux");
    model.component("comp1").physics("ht").feature("hf2").set("h", "h_conv");
    model.component("comp1").physics("ht").feature("hf2").set("Text", "T_amb");
    model.component("comp1").physics("ht").feature("hf2").set("materialType", "solid");
    model.component("comp1").physics("ht").feature("sar1").set("epsilon_rad_mat", "userdef");
    model.component("comp1").physics("ht").feature("sar1").set("epsilon_rad", "eps_surf");
    model.component("comp1").physics("ht").feature("sar1").set("Tamb", "T_amb");
    model.component("comp1").physics("dode").prop("EquationForm").set("form", "Automatic");
    model.component("comp1").physics("dode").prop("Units").set("CustomSourceTermUnit", "1/s");
    model.component("comp1").physics("dode").feature("dode1").set("f", "f_py");
    model.component("comp1").physics("dode2").prop("EquationForm").set("form", "Automatic");

    return model;
  }

  public static Model run2(Model model) {
    model.component("comp1").physics("dode2").prop("Units").set("CustomSourceTermUnit", "1/s");
    model.component("comp1").physics("dode2").feature("dode1").set("f", "dalphac_dt_kin * scale_O2_m");
    model.component("comp1").physics("dode3").prop("EquationForm").set("form", "Automatic");
    model.component("comp1").physics("dode3").prop("Units").set("CustomSourceTermUnit", "1/s");
    model.component("comp1").physics("dode3").feature("dode1").set("f", "dalphaf_dt_kin*scale_O2_m");
    model.component("comp1").physics("dg").prop("FreeDeformationSettings").set("smoothingType", "hyperelastic");
    model.component("comp1").physics("dg").feature("pnmv1").set("vn", "-((v_mesh + v_sub))");
    model.component("comp1").physics("dg").feature("pnmv1").set("embs", true);
    model.component("comp1").physics("dg").feature("disp3").set("useDx", new int[][]{{1}, {0}, {0}});
    model.component("comp1").physics("dg").feature("disp4").set("useDx", new int[][]{{0}, {1}, {0}});

    model.component("comp1").mesh("mesh1").feature("swe1").set("facemethod", "tri");
    model.component("comp1").mesh("mesh1").feature("swe1").selection("sourceface").set(4, 6);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size1").set("custom", "on");
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size1").set("hmax", 0.8);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size1").set("hmaxactive", true);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size1").set("hmin", 0.002);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size1").set("hminactive", true);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size1").set("hcurve", 0.2);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size1").set("hgrad", 1.3);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size1").set("hgradactive", true);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size1").set("hcurveactive", false);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").set("custom", "on");
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").set("hmax", 0.1);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").set("hmaxactive", true);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").set("hmin", 0.002);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").set("hminactive", true);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").set("hcurve", 0.4);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").set("hgrad", 1.3);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").set("hgradactive", true);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("size2").set("hcurveactive", false);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("dis1").set("type", "predefined");
    model.component("comp1").mesh("mesh1").feature("swe1").feature("dis1").set("elemcount", 15);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("dis1").set("elemratio", 8);
    model.component("comp1").mesh("mesh1").feature("swe1").feature("dis1").set("growthrate", "exponential");
    model.component("comp1").mesh("mesh1").feature("swe2").active(false);
    model.component("comp1").mesh("mesh1").run();

    model.component("comp1").probe("bnd1").set("descractive", true);
    model.component("comp1").probe("bnd1").set("descr", "\u5c0f\u533a\u57df\u5e73\u5747\u6e29\u5ea6");
    model.component("comp1").probe("bnd1").set("frame", "spatial");
    model.component("comp1").probe("bnd1").set("table", "tbl1");
    model.component("comp1").probe("bnd1").set("window", "window2");
    model.component("comp1").probe("bnd2").set("type", "maximum");
    model.component("comp1").probe("bnd2").set("descractive", true);
    model.component("comp1").probe("bnd2").set("descr", "\u6700\u5927\u6e29\u5ea6");
    model.component("comp1").probe("bnd2").set("frame", "spatial");
    model.component("comp1").probe("bnd2").set("table", "tbl1");
    model.component("comp1").probe("bnd2").set("window", "window2");
    model.component("comp1").probe("bnd3").set("type", "maximum");
    model.component("comp1").probe("bnd3").set("expr", "v_mesh + v_sub");
    model.component("comp1").probe("bnd3").set("unit", "m/s");
    model.component("comp1").probe("bnd3").set("descractive", true);
    model.component("comp1").probe("bnd3").set("descr", "\u6700\u5927\u901f\u5ea6");
    model.component("comp1").probe("bnd3").set("frame", "spatial");
    model.component("comp1").probe("bnd3").set("table", "tbl1");
    model.component("comp1").probe("bnd3").set("window", "window2");
    model.component("comp1").probe("dom1").set("type", "maximum");
    model.component("comp1").probe("dom1").set("expr", "alphap");
    model.component("comp1").probe("dom1").set("unit", "1");
    model.component("comp1").probe("dom1").set("descractive", true);
    model.component("comp1").probe("dom1").set("descr", "\u56e0\u53d8\u91cf alphap");
    model.component("comp1").probe("dom1").set("frame", "spatial");
    model.component("comp1").probe("dom1").set("table", "tbl1");
    model.component("comp1").probe("dom1").set("window", "window2");
    model.component("comp1").probe("dom2").set("type", "minimum");
    model.component("comp1").probe("dom2").set("expr", "alphap");
    model.component("comp1").probe("dom2").set("unit", "1");
    model.component("comp1").probe("dom2").set("descractive", true);
    model.component("comp1").probe("dom2").set("descr", "\u56e0\u53d8\u91cf alphap");
    model.component("comp1").probe("dom2").set("frame", "spatial");
    model.component("comp1").probe("dom2").set("table", "tbl1");
    model.component("comp1").probe("dom2").set("window", "window2");
    model.component("comp1").probe("dom3").set("type", "maximum");
    model.component("comp1").probe("dom3").set("descractive", true);
    model.component("comp1").probe("dom3").set("descr", "\u5168\u5c40\u6700\u5927\u6e29\u5ea6");
    model.component("comp1").probe("dom3").set("table", "tbl1");
    model.component("comp1").probe("dom3").set("window", "window2");
    model.component("comp1").probe("dom4").set("type", "maximum");
    model.component("comp1").probe("dom4").set("probename", "Max_vmesh");
    model.component("comp1").probe("dom4").set("expr", "v_mesh");
    model.component("comp1").probe("dom4").set("unit", "m/s");
    model.component("comp1").probe("dom4").set("descractive", true);
    model.component("comp1").probe("dom4").set("descr", "Max_vmesh");
    model.component("comp1").probe("dom4").set("table", "tbl1");
    model.component("comp1").probe("dom4").set("window", "window2");
    model.component("comp1").probe("dom5").set("probename", "Int_Qox");
    model.component("comp1").probe("dom5").set("expr", "Q_ox_char+Q_ox_fib");
    model.component("comp1").probe("dom5").set("unit", "W/cm^3");
    model.component("comp1").probe("dom5").set("descractive", true);
    model.component("comp1").probe("dom5").set("descr", "\u6c27\u5316\u653e\u70ed\u603b\u529f\u7387");
    model.component("comp1").probe("dom5").set("table", "tbl1");
    model.component("comp1").probe("dom5").set("window", "window2");
    model.component("comp1").probe("dom6").set("descractive", true);
    model.component("comp1").probe("dom6").set("descr", "\u6700\u5c0f\u7f51\u683c\u8d28\u91cf");
    model.component("comp1").probe("dom6").set("table", "tbl1");
    model.component("comp1").probe("dom6").set("window", "window2");
    model.component("comp1").probe("dom7").set("type", "minimum");
    model.component("comp1").probe("dom7").set("expr", "scale_O2");
    model.component("comp1").probe("dom7").set("unit", "1");
    model.component("comp1").probe("dom7").set("descractive", true);
    model.component("comp1").probe("dom7").set("descr", "\u6c27\u901a\u91cf");
    model.component("comp1").probe("dom7").set("table", "tbl1");
    model.component("comp1").probe("dom7").set("window", "window2");
    model.component("comp1").probe("bnd4").set("expr", "v_pyro");
    model.component("comp1").probe("bnd4").set("unit", "m/s");
    model.component("comp1").probe("bnd4").set("descr", "");
    model.component("comp1").probe("bnd4").set("table", "tbl1");
    model.component("comp1").probe("bnd4").set("window", "window1");
    model.component("comp1").probe("bnd5").set("type", "maximum");
    model.component("comp1").probe("bnd5").set("descractive", true);
    model.component("comp1").probe("bnd5").set("descr", "\u80cc\u677f\u6700\u5927\u6e29\u5ea6");
    model.component("comp1").probe("bnd5").set("table", "tbl1");
    model.component("comp1").probe("bnd5").set("window", "window3");

    model.study().create("std1");
    model.study("std1").create("time", "Transient");
    model.study("std1").feature("time").set("plot", true);

    model.sol().create("sol1");
    model.sol("sol1").attach("std1");
    model.sol("sol1").create("st1", "StudyStep");
    model.sol("sol1").create("v1", "Variables");
    model.sol("sol1").create("t1", "Time");
    model.sol("sol1").feature("t1").create("se1", "Segregated");
    model.sol("sol1").feature("t1").create("d1", "Direct");
    model.sol("sol1").feature("t1").create("i1", "Iterative");
    model.sol("sol1").feature("t1").feature("se1").create("ss1", "SegregatedStep");
    model.sol("sol1").feature("t1").feature("se1").create("ss2", "SegregatedStep");
    model.sol("sol1").feature("t1").feature("se1").create("ss3", "SegregatedStep");
    model.sol("sol1").feature("t1").feature("se1").create("ss4", "SegregatedStep");
    model.sol("sol1").feature("t1").feature("se1").create("ss5", "SegregatedStep");
    model.sol("sol1").feature("t1").feature("se1").create("ll1", "LowerLimit");
    model.sol("sol1").feature("t1").feature("se1").feature().remove("ssDef");
    model.sol("sol1").feature("t1").feature("i1").create("mg1", "Multigrid");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("pr").create("so1", "SOR");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("po").create("so1", "SOR");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("cs").create("d1", "Direct");
    model.sol("sol1").feature("t1").feature().remove("fcDef");
    model.sol().create("sol2");
    model.sol("sol2").study("std1");
    model.sol().create("sol3");
    model.sol("sol3").study("std1");

    model.result().dataset().create("mesh1", "Mesh");
    model.result().dataset().create("an5_ds1", "Grid2D");
    model.result().dataset().create("avh1", "Average");
    model.result().dataset().create("max1", "Maximum");
    model.result().dataset().create("max2", "Maximum");
    model.result().dataset().create("max3", "Maximum");
    model.result().dataset().create("min1", "Minimum");
    model.result().dataset().create("dset4", "Solution");
    model.result().dataset().create("max4", "Maximum");
    model.result().dataset().create("max5", "Maximum");
    model.result().dataset().create("avh2", "Average");
    model.result().dataset().create("avh3", "Average");
    model.result().dataset().create("min2", "Minimum");
    model.result().dataset().create("avh4", "Average");
    model.result().dataset().create("dset5", "Solution");
    model.result().dataset().create("avh5", "Average");
    model.result().dataset().create("max6", "Maximum");
    model.result().dataset().create("max7", "Maximum");
    model.result().dataset().create("max8", "Maximum");
    model.result().dataset().create("min3", "Minimum");
    model.result().dataset().create("max9", "Maximum");
    model.result().dataset().create("max10", "Maximum");
    model.result().dataset().create("avh6", "Average");
    model.result().dataset().create("avh7", "Average");
    model.result().dataset().create("min4", "Minimum");
    model.result().dataset().create("avh8", "Average");
    model.result().dataset().create("dset6", "Solution");
    model.result().dataset().create("max11", "Maximum");
    model.result().dataset("an5_ds1").set("data", "none");
    model.result().dataset("dset3").set("probetag", "bnd5");
    model.result().dataset("dset3").set("solution", "sol1");
    model.result().dataset("dset5").set("probetag", "dom2");
    model.result().dataset("avh5").set("probetag", "bnd1");
    model.result().dataset("avh5").set("data", "dset5");
    model.result().dataset("avh5").selection().geom("geom1", 2);
    model.result().dataset("avh5").selection().set(6);
    model.result().dataset("max6").set("probetag", "bnd2");
    model.result().dataset("max6").set("data", "dset5");
    model.result().dataset("max6").selection().geom("geom1", 2);
    model.result().dataset("max6").selection().set(4, 6);
    model.result().dataset("max7").set("probetag", "bnd3");
    model.result().dataset("max7").set("data", "dset5");
    model.result().dataset("max7").selection().geom("geom1", 2);
    model.result().dataset("max7").selection().set(4, 6);
    model.result().dataset("max8").set("probetag", "dom1");
    model.result().dataset("max8").set("data", "dset5");
    model.result().dataset("max8").selection().geom("geom1", 3);
    model.result().dataset("max8").selection().set(1);
    model.result().dataset("min3").set("probetag", "dom2");
    model.result().dataset("min3").set("data", "dset5");
    model.result().dataset("min3").selection().geom("geom1", 3);
    model.result().dataset("min3").selection().set(1);
    model.result().dataset("max9").set("probetag", "dom3");
    model.result().dataset("max9").set("data", "dset3");
    model.result().dataset("max9").selection().geom("geom1", 3);
    model.result().dataset("max9").selection().set(1);
    model.result().dataset("max10").set("probetag", "dom4");
    model.result().dataset("max10").set("data", "dset3");
    model.result().dataset("max10").selection().geom("geom1", 3);
    model.result().dataset("max10").selection().set(1);
    model.result().dataset("avh6").set("probetag", "dom5");
    model.result().dataset("avh6").set("data", "dset3");
    model.result().dataset("avh6").selection().geom("geom1", 3);
    model.result().dataset("avh6").selection().set(1);
    model.result().dataset("avh7").set("probetag", "dom6");
    model.result().dataset("avh7").set("data", "dset3");
    model.result().dataset("avh7").selection().geom("geom1", 3);
    model.result().dataset("avh7").selection().set(1);
    model.result().dataset("min4").set("probetag", "dom7");
    model.result().dataset("min4").set("data", "dset3");
    model.result().dataset("min4").selection().geom("geom1", 3);
    model.result().dataset("min4").selection().set(1);
    model.result().dataset("avh8").set("probetag", "bnd4");
    model.result().dataset("avh8").set("data", "dset3");
    model.result().dataset("avh8").selection().geom("geom1", 2);
    model.result().dataset("avh8").selection().set(1, 2, 3, 4, 5, 6, 7);
    model.result().dataset("dset6").set("solution", "sol3");
    model.result().dataset("max11").set("probetag", "bnd5");
    model.result().dataset("max11").set("data", "dset3");
    model.result().dataset("max11").selection().geom("geom1", 2);
    model.result().dataset("max11").selection().set(3);
    model.result().numerical().create("pev1", "EvalPoint");
    model.result().numerical().create("pev2", "EvalPoint");
    model.result().numerical().create("pev3", "EvalPoint");
    model.result().numerical().create("pev4", "EvalPoint");
    model.result().numerical().create("pev5", "EvalPoint");
    model.result().numerical().create("pev6", "EvalPoint");
    model.result().numerical().create("pev7", "EvalPoint");
    model.result().numerical().create("pev8", "EvalPoint");
    model.result().numerical().create("pev9", "EvalPoint");
    model.result().numerical().create("pev10", "EvalPoint");
    model.result().numerical().create("pev11", "EvalPoint");
    model.result().numerical().create("pev12", "EvalPoint");
    model.result().numerical().create("pev13", "EvalPoint");
    model.result().numerical("pev2").set("probetag", "bnd1");
    model.result().numerical("pev3").set("probetag", "bnd2");
    model.result().numerical("pev4").set("probetag", "bnd3");
    model.result().numerical("pev5").set("probetag", "dom1");
    model.result().numerical("pev6").set("probetag", "dom2");
    model.result().numerical("pev7").set("probetag", "dom3");
    model.result().numerical("pev8").set("probetag", "dom4");
    model.result().numerical("pev9").set("probetag", "dom5");
    model.result().numerical("pev10").set("probetag", "dom6");
    model.result().numerical("pev11").set("probetag", "dom7");
    model.result().numerical("pev12").set("probetag", "bnd4");
    model.result().numerical("pev13").set("probetag", "bnd5");

    model.component("comp1").probe("bnd1").genResult(null);
    model.component("comp1").probe("bnd2").genResult(null);
    model.component("comp1").probe("bnd3").genResult(null);
    model.component("comp1").probe("dom1").genResult(null);
    model.component("comp1").probe("dom2").genResult(null);
    model.component("comp1").probe("dom3").genResult(null);
    model.component("comp1").probe("dom4").genResult(null);
    model.component("comp1").probe("dom5").genResult(null);
    model.component("comp1").probe("dom6").genResult(null);
    model.component("comp1").probe("dom7").genResult(null);
    model.component("comp1").probe("bnd4").genResult(null);
    model.component("comp1").probe("bnd5").genResult(null);

    model.study("std1").feature("time").set("tlist", "range(0,0.1,100)");
    model.study("std1").feature("time").set("plotgroup", "Default");

    model.sol("sol1").feature("st1").label("\u7f16\u8bd1\u65b9\u7a0b: \u77ac\u6001");
    model.sol("sol1").feature("v1").label("\u56e0\u53d8\u91cf 1.1");
    model.sol("sol1").feature("v1").set("clist", new String[]{"{range(0, 0.1, 100)}[s]", "0.1[s]"});
    model.sol("sol1").feature("t1").label("\u77ac\u6001\u6c42\u89e3\u5668 1.1");
    model.sol("sol1").feature("t1").set("tlist", "range(0,0.1,100)");
    model.sol("sol1").feature("t1").set("plot", true);
    model.sol("sol1").feature("t1").feature("dDef").label("\u76f4\u63a5 2");
    model.sol("sol1").feature("t1").feature("aDef").label("\u9ad8\u7ea7 1");
    model.sol("sol1").feature("t1").feature("se1").label("\u5206\u79bb 1.1");
    model.sol("sol1").feature("t1").feature("se1").feature("ss1").label("\u5206\u79bb\u6b65\u9aa4 1.1");
    model.sol("sol1").feature("t1").feature("se1").feature("ss2").label("\u5206\u79bb\u6b65\u9aa4 2.1");
    model.sol("sol1").feature("t1").feature("se1").feature("ss3").label("\u5206\u79bb\u6b65\u9aa4 3.1");
    model.sol("sol1").feature("t1").feature("se1").feature("ss4").label("\u5206\u79bb\u6b65\u9aa4 4.1");
    model.sol("sol1").feature("t1").feature("se1").feature("ss5").label("\u5206\u79bb\u6b65\u9aa4 5.1");
    model.sol("sol1").feature("t1").feature("se1").feature("ll1").label("\u4e0b\u9650 1.1");
    model.sol("sol1").feature("t1").feature("d1").label("\u76f4\u63a5 1.1");
    model.sol("sol1").feature("t1").feature("i1").label("\u8fed\u4ee3 1.1");
    model.sol("sol1").feature("t1").feature("i1").feature("ilDef").label("\u4e0d\u5b8c\u5168 LU \u5206\u89e3 1");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").label("\u591a\u91cd\u7f51\u683c 1.1");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("pr").label("\u9884\u5e73\u6ed1\u5668 1");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("pr").feature("soDef").label("SOR 2");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("pr").feature("so1").label("SOR 1.1");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("po").label("\u540e\u5e73\u6ed1\u5668 1");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("po").feature("soDef").label("SOR 2");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("po").feature("so1").label("SOR 1.1");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("cs")
         .label("\u7c97\u5316\u6c42\u89e3\u5668 1");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("cs").feature("dDef")
         .label("\u76f4\u63a5 2");
    model.sol("sol1").feature("t1").feature("i1").feature("mg1").feature("cs").feature("d1")
         .label("\u76f4\u63a5 1.1");
    model.sol("sol3").label("\u91cd\u65b0\u5212\u5206\u7f51\u683c\u540e\u7684\u89e3 1");
    model.sol("sol3").runAll();

    model.study("std1").runNoGen();

    model.result().dataset().create("dset5", "Solution");
    model.result().dataset("dset5").label("\u63a2\u9488\u89e3 5");
    model.result().dataset("dset5").set("frametype", "spatial");
    model.result().dataset("avh5").set("data", "dset5");
    model.result().dataset("max6").set("data", "dset5");
    model.result().dataset("max7").set("data", "dset5");
    model.result().dataset("max8").set("data", "dset5");
    model.result().dataset("min3").set("data", "dset5");
    model.result().dataset().remove("dset7");
    model.result().numerical("pev1").set("data", "none");
    model.result().numerical("pev1").set("expr", new String[]{"comp1.T", "alphap", "alphac", "alphaf"});
    model.result().numerical("pev1").set("unit", new String[]{"K", "", "", ""});
    model.result().numerical("pev4").set("unit", new String[]{"m/s"});
    model.result().numerical("pev8").set("unit", new String[]{"m/s"});
    model.result().numerical("pev11").set("unit", new String[]{"1"});
    model.result().numerical("pev13").setResult();
    model.result().remove("pg1");
    model.result().remove("pg2");
    model.result().remove("pg3");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
